### ISSUE TITLE
Frederic Brilliant!

### ISSUE THREAD

**Issue by agentbond007** [Langhalsdino/Kubernetes-GPU-Guide#3]
Absolutely brilliant work Frederic with this repo.  Reminds me of pipeline.io efforts.  Thank you for your contribution.

**Comment by Langhalsdino** [comment]
Thank you for the feedback.

Pipeline.io efforts are in the same space, but head of to a specialized platform. 
On the other side Kubernetes takes a more generalized approach on distributed computing, that allows a higher degree of customisation. Therefore, if you need distributed computing for other applications, it might be easier to build only one Kubernetes Infrastructure, than dealing with two systems. But this is only reasonable to certain extend. 

Overall, i am looking forward to the beta of pipeline.io and see how it performs.
